# Generated by Django 5.0.7 on 2024-08-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_company_options_alter_phone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_data', models.DateField(verbose_name='Дата поставки')),
                ('delivery_price', models.FloatField(verbose_name='Цена')),
                ('delivery_count', models.FloatField(default=1, verbose_name='Количество поставок')),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.phone')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.company')),
            ],
        ),
    ]
