# Generated by Django 5.0.7 on 2024-08-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='delivery_number',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер поставки'),
            preserve_default=False,
        ),
    ]
