# Generated by Django 5.0.7 on 2024-08-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Telephon',
            new_name='Phone',
        ),
    ]
