# Generated by Django 5.0.7 on 2024-08-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_company_phone_photo_phone_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
    ]
